"""create profiles table

Revision ID: e1592ba31b6c
Revises: 3143fe1d4050
Create Date: 2026-05-21 15:27:06.380882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1592ba31b6c'
down_revision: Union[str, Sequence[str], None] = '3143fe1d4050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cats', sa.Column('breed', sa.String(), nullable=True))
    op.add_column('cats', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('cats', sa.Column('description', sa.String(), nullable=True))
    op.add_column('cats', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('cats', 'created_at')
    op.drop_column('cats', 'description')
    op.drop_column('cats', 'age')
    op.drop_column('cats', 'breed')
    # ### end Alembic commands ###
